version: '3.7'

services:
  num-app:
    image: time-app:v1
    ports:
      - 3030:5000
        # НЕТ mode: host!
    deploy:
      replicas: 4
    networks:
      - time-net

networks:
  time-net:
    driver: overlay