name: Test /time endpoint

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        shell: powershell
        run: |
          python -m venv venv
          .\venv\Scripts\python -m pip install -r requirements.txt
          .\venv\Scripts\python -m pip install requests

      - name: Run app in background
        shell: powershell
        run: |
          Start-Process -NoNewWindow .\venv\Scripts\python -ArgumentList "src/app/app.py"
          Start-Sleep -Seconds 2

      - name: Run test
        shell: powershell
        run: |
          .\venv\Scripts\python test/test_time.py